# Generated by Django 5.2.6 on 2025-12-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='course',
        ),
    ]
