# Generated by Django 5.2.6 on 2025-12-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0002_alter_certificate_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
