# Generated by Django 5.2.6 on 2025-12-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0003_alter_certificate_certificate_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_available_certificate',
            field=models.BooleanField(default=True),
        ),
    ]
