# Generated by Django 5.2.6 on 2025-12-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0004_certificate_is_available_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='is_available_certificate',
            field=models.BooleanField(default=False),
        ),
    ]
