# Generated by Django 5.2.6 on 2025-12-10 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0005_alter_certificate_is_available_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newadmissionapplication',
            name='student_registration',
        ),
    ]
