# Generated by Django 5.2.6 on 2025-12-10 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0006_remove_newadmissionapplication_student_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate_no',
            new_name='certificate_regd_no',
        ),
    ]
