# Generated by Django 5.2.6 on 2025-12-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0007_rename_certificate_no_certificate_certificate_regd_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_template',
            field=models.FileField(blank=True, null=True, upload_to='certificate_template/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course_coodinator',
            field=models.FileField(blank=True, null=True, upload_to='course_coordinator/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='excutive_head_signature_image',
            field=models.FileField(blank=True, null=True, upload_to='executive_head_signature/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_course_coodinator_active',
            field=models.BooleanField(default=False, verbose_name='Active Course Coordinator Signature'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_excutive_head_signature_active',
            field=models.BooleanField(default=False, verbose_name='Active Executive Head Signature'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_shop_stamp_active',
            field=models.BooleanField(default=False, verbose_name='Active Shop Stamp'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='shop_stamp_image',
            field=models.FileField(blank=True, null=True, upload_to='shop_stamp/'),
        ),
    ]
