# Generated by Django 5.2.6 on 2025-12-10 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0008_certificate_certificate_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='certificate',
        ),
    ]
