# Generated by Django 5.2.6 on 2025-12-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0009_remove_website_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='status',
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_watermark_active',
            field=models.BooleanField(default=True, verbose_name='Active Watermark'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='watermark_text',
            field=models.CharField(blank=True, default='OFFICIAL', max_length=50, null=True),
        ),
    ]
