# Generated by Django 5.2.6 on 2025-12-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0012_remove_certificate_certificate_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='certificate_template',
        ),
        migrations.RemoveField(
            model_name='website',
            name='course_coodinator',
        ),
        migrations.RemoveField(
            model_name='website',
            name='discord',
        ),
        migrations.RemoveField(
            model_name='website',
            name='excutive_head_signature_image',
        ),
        migrations.RemoveField(
            model_name='website',
            name='github',
        ),
        migrations.RemoveField(
            model_name='website',
            name='insta',
        ),
        migrations.RemoveField(
            model_name='website',
            name='pinterest',
        ),
        migrations.RemoveField(
            model_name='website',
            name='reddit',
        ),
        migrations.RemoveField(
            model_name='website',
            name='shop_stamp_image',
        ),
        migrations.RemoveField(
            model_name='website',
            name='snapchat',
        ),
        migrations.RemoveField(
            model_name='website',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='website',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='website',
            name='youtube',
        ),
        migrations.AddField(
            model_name='website',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Enter your WhatsApp number in international format (e.g., +977XXXXXXXXX)', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='android_app',
            field=models.FileField(blank=True, null=True, upload_to='apps/android/'),
        ),
        migrations.AlterField(
            model_name='website',
            name='desktop_app',
            field=models.FileField(blank=True, null=True, upload_to='apps/desktop/'),
        ),
        migrations.AlterField(
            model_name='website',
            name='ios_app',
            field=models.FileField(blank=True, null=True, upload_to='apps/ios/'),
        ),
    ]
