# Generated by Django 5.2.6 on 2025-12-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0013_remove_website_certificate_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='whatsapp',
        ),
    ]
