# Generated by Django 5.2.6 on 2025-12-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0014_remove_website_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_file',
        ),
    ]
