# Generated by Django 5.2.6 on 2025-12-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0015_remove_certificate_certificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='certificate_template',
            field=models.FileField(blank=True, null=True, upload_to='certificate_template/'),
        ),
        migrations.AddField(
            model_name='website',
            name='course_coodinator',
            field=models.FileField(blank=True, null=True, upload_to='course_coordinator/'),
        ),
        migrations.AddField(
            model_name='website',
            name='excutive_head_signature_image',
            field=models.FileField(blank=True, null=True, upload_to='executive_head_signature/'),
        ),
        migrations.AddField(
            model_name='website',
            name='shop_stamp_image',
            field=models.FileField(blank=True, null=True, upload_to='shop_stamp/'),
        ),
    ]
