"""
Django settings for Gurukul project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from django.core.files.storage import FileSystemStorage
from pathlib import Path
from environ import Env

env = Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v++3j)l$0y2-2)cj4ou-si2mha0fhwil29g(dhu+7j2)9o%v(x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.twitter',
    'django.contrib.messages', 'corsheaders',
    'django.contrib.staticfiles', 'django.contrib.sites', 'MainApps',  'Authentications', 'django_ckeditor_5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    
]

ROOT_URLCONF = 'Gurukul.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'MainApps.context_processors.website_info',
                'Authentications.context_processors.website_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'Gurukul.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default
    'allauth.account.auth_backends.AuthenticationBackend',  # allauth
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# URL path to access static files in browser
STATIC_URL = '/static/'

# In production, collect all static files here
STATIC_ROOT = BASE_DIR / "staticfiles"


# URL prefix for media files (uploads)
MEDIA_URL = '/media/'

# Folder where uploaded files will be saved
MEDIA_ROOT = BASE_DIR / "media"  # Make sure this folder exists

# ------------------------
# EXAMPLE DIRECTORY STRUCTURE
# ------------------------
# Your project folder should look like this:
#
# Gurukul project/
# ├─ Gurukul/
# │  ├─ settings.py
# │  └─ ...
# ├─ static/
# │  ├─ css/
# │  ├─ js/
# │  └─ images/
# ├─ media/
# │  └─ uploads/
# ├─ manage.py
# └─ ...


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS for React dev server
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

X_FRAME_OPTIONS = 'ALLOWALL'  # For testing only; change in production


customColorPalette = [
    {
        'color': 'hsl(4, 90%, 58%)',
        'label': 'Red'
    },
    {
        'color': 'hsl(340, 82%, 52%)',
        'label': 'Pink'
    },
    {
        'color': 'hsl(291, 64%, 42%)',
        'label': 'Purple'
    },
    {
        'color': 'hsl(262, 52%, 47%)',
        'label': 'Deep Purple'
    },
    {
        'color': 'hsl(231, 48%, 48%)',
        'label': 'Indigo'
    },
    {
        'color': 'hsl(207, 90%, 54%)',
        'label': 'Blue'
    },
]

# Storage for uploaded files


# ----------------------------
# Custom Storage for CKEditor
# ----------------------------
class CustomStorage(FileSystemStorage):
    location = MEDIA_ROOT / "Blogs/gallery/"
    base_url = MEDIA_URL + "Blogs/gallery/"

# ----------------------------
# CKEditor 5 Settings
# ----------------------------
CKEDITOR_5_FILE_STORAGE = "Gurukul.settings.CustomStorage"  # Full module path
CKEDITOR_5_UPLOAD_PATH = "uploads/files/"                  # Relative path inside MEDIA_ROOT
CKEDITOR_5_FILE_UPLOAD = True
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "authenticated"       # staff, authenticated, any

# ----------------------------
# CKEditor Toolbar & Plugins
# ----------------------------
customColorPalette = [
    {'color': '#000000', 'label': 'Black'},
    {'color': '#FF0000', 'label': 'Red'},
    {'color': '#00FF00', 'label': 'Green'},
    {'color': '#0000FF', 'label': 'Blue'},
]

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': {
            'items': [
                'heading', '|',
                'bold', 'italic', 'underline', 'strikethrough', 'link',
                'bulletedList', 'numberedList', 'todoList', '|',
                'outdent', 'indent', '|',
                'blockQuote', 'code', 'codeBlock', 'insertTable', 'imageUpload', 'mediaEmbed', '|',
                'fontColor', 'fontBackgroundColor', 'fontSize', 'fontFamily', 'highlight', '|',
                'horizontalLine', 'pageBreak', '|',
                'undo', 'redo', 'sourceEditing', 'removeFormat'
            ],
            'shouldNotGroupWhenFull': True
        },
        'image': {
            'toolbar': [
                'imageTextAlternative', '|',
                'imageStyle:alignLeft', 'imageStyle:alignCenter', 'imageStyle:alignRight'
            ]
        },
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells', 'tableProperties', 'tableCellProperties'
            ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'codeBlock': {
            'languages': [
                {'language': 'python', 'label': 'Python'},
                {'language': 'javascript', 'label': 'JavaScript'},
                {'language': 'html', 'label': 'HTML'},
                {'language': 'css', 'label': 'CSS'},
            ]
        },
        'mediaEmbed': {
            'previewsInData': True
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3'}
            ]
        },
        'list': {
            'properties': {
                'styles': True,
                'startIndex': True,
                'reversed': True
            }
        }
    }
}

# ----------------------------
# Django Auth / Social Login
# ----------------------------
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "/"
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


SITE_ID = 1

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': env("OAUTH_GOOGLE_CLIENT_ID"),
            'secret': env("OAUTH_GOOGLE_CLIENT_SECRET"),
            'key': '',
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

SOCIALACCOUNT_LOGIN_ON_GET = True
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'


# settings.py

# Khalti Sandbox
KHALTI_PUBLIC_KEY = 'f6cbb69af4ad44d6b2ed4ad0e42fdd02'
KHALTI_SECRET_KEY = "225f770c8e6047bbb831b5374e7e27f7"

# --- Add this line ---
# This must match the 'khalti_success' URL pattern defined in your urls.py
KHALTI_SUCCESS_URL = f"http://127.0.0.1:8000/payment/khalti/success/" 
KHALTI_FAILURE_URL = "http://127.0.0.1:8000/payment/khalti/failure/"
# ---------------------

# esewa Sandbox
ESEWA_BASE_URL = "https://rc-epay.esewa.com.np/api/epay/main/v2/form"
ESEWA_SUCCESS_URL = "http://127.0.0.1:8000/payment/esewa/success/" 
ESEWA_FAILURE_URL = "http://127.0.0.1:8000/payment-failure/"
ESEWA_SECRET_KEY = "8gBm/:&EnhH.1/q"


# 2. Define the Whitelist of public URL paths (add paths, NOT names)
PUBLIC_URLS = (
    '/',                                    # Home
    '/login/',                              # Auth: Login
    '/logout/',                             # Auth: Logout
    '/signup/',                             # Auth: Registration (if applicable)
    '/product-list/',                       # Product Listing
    '/course-list/',                        # Course Listing
    '/blog-list/',                          # Blog Listing
    '/contact-us/',                         # Contact Page
    '/search/',                             # Search Results
    '/about-us/',                           # About Us
    '/service-pricing/',                    # Service Pricing
    '/shipping-delivery-info/',             # Shipping Info
    '/static/',
    '/media/',
    # Required for static/media files and error pages (optional but recommended)

    # Standard URLs that may be required by the AUTH app
    '/admin/login/',                        # Django Admin Login
    '/password_reset/',
    '/password_reset/done/',
    '/reset/',
    '/reset/done/',
)